### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by shreevatsa** [shreevatsa/knuth-literate-programs#1]
I should clean up this repo; just jotting down here some ideas for next steps, as I don't have the time to spend on this right now:

* [ ] Keep it up to date. (Last updated today, 2023-05-28.) Run `make` (runs `get-all.py`) manually from time to time, or automate the whole thing.

    - A GitHub workflow can be used to keep things up to date. There are some beginnings in `parse.py` in branch `auto`.
    - In particular the `index.md` should be automatically generated; otherwise it's very old and missing recent programs.

* [x] ~~Use GitHub pages to have direct links to the PDFs (i.e. should be possible to link to the PDF in a browser). Without it, one only has GitHub's rendering, but that's not searchable, and can't link directly to a page or section.~~ (Done 2023-05-28: e.g. https://shreevatsa.github.io/knuth-literate-programs/programs/cvm-estimates.pdf )

* [x] ~~Maybe: Have a version of https://cs.stanford.edu/~knuth/programs.html in which the links are to the PDFs instead. (Would have to be very clear that this is not the real page, and link back to it.) Would also save the effort of documenting what these programs are.~~ (Done 2023-05-28: https://shreevatsa.github.io/knuth-literate-programs/programs/)

* [ ] Add some words about literate programming, introduction, links to the original papers, the WEB (not CWEB) programs, etc.
